### ISSUE TITLE
Inconsistency in combined_maxdose & Significant_Genes_by_Treatment

### ISSUE THREAD

**Issue by gr8lly8** [jshousephd/HT-CBA#1]
Hello, 

I have been trying to replicate your pipeline with your data in my R and have found two stumbling blocks I'm hoping you might be able to help me with:

1) the values produced seems to be a little different.  A good example is Significant_Genes_by_Treatment.  In your output you have the following values:

Treatment | Direction | Gene_number | mean_abslog2fc | median_abslog2fc | Significance_Level
-- | -- | -- | -- | -- | --
Nifedipine | Down | 470 | 0.797468 | 0.785502 | 0.1
Nifedipine | Up | 448 | 0.66246 | 0.625408 | 0.1
Dofetilide | Down | 231 | 0.678229 | 0.636184 | 0.1
Dofetilide | Up | 194 | 0.695115 | 0.635155 | 0.1
Isoproterenol | Down | 21 | 0.817671 | 0.754112 | 0.1
Propranolol | Down | 19 | 1.152384 | 1.175495 | 0.1
Isoproterenol | Up | 11 | 0.646818 | 0.575535 | 0.1
Propranolol | Up | 10 | 0.60611 | 0.502549 | 0.1

Where as I am getting: 

Treatment | Direction | Gene_number | mean_abslog2fc | median_abslog2fc | Significance_Level
-- | -- | -- | -- | -- | --
Nifedipine | Down | 484 | 0.964297 | 0.898591 | 0.1
Nifedipine | Up | 456 | 0.811728 | 0.661514 | 0.1
Dofetilide | Down | 232 | 0.748158 | 0.677118 | 0.1
Dofetilide | Up | 210 | 0.984976 | 0.730503 | 0.1
Isoproterenol | Down | 20 | 0.927427 | 0.760468 | 0.1
Propranolol | Down | 16 | 1.551687 | 1.55746 | 0.1
Isoproterenol | Up | 13 | 0.691197 | 0.622255 | 0.1
Propranolol | Up | 6 | 0.743561 | 0.523919 | 0.1

There are (perhaps unsurprisingly) some version differences in the packages between my system and the system you've used.  Have you tried this on any other versions of R/with other packages and are able to point me in the direction of a likely cause? I am trying to avoid going through 100 packages one by one and finding the older version!

2) In script four line 24 I get an error relating to there not being enough columns for the headers provided.  It is in response to this code:
counts <- gather(normcounts, "X", "NormCounts") 
names(counts) <- c("Gene", "header", "NormCounts")

If I change it to the below it seems to be working: 
counts <- tidyr::gather(normcounts, header, value, -X) 

I am not sure if this is also a version issue? 

Any hits and tips would be much appreciated :) 

Many Thanks,
Grace

**Comment by jshousephd** [comment]
1) This is likely due to changes in DESeq2 and its defaults and implementation of `lfcShrink()` and the changes discussed here: https://support.bioconductor.org/p/95695/

Try the version of DESeq2 I posted in the manuscript and let me know if that fixes the issue.
DESeq2_1.14.1
2) `gather` has changed enough that I've had to alter code as well similar to what you have done in the last 24 months. I am pretty sure this is a versioning issue, but your solution is fine.


Best,
john

**Comment by gr8lly8** [comment]
Hi John, 

Thank you for the advice.  If I install the old DESeq2 I have all sorts of other problems with versions.  How do you feel about using the new DESeq2 without the lfcShrink function?

Thanks, 
Grace

**Comment by jshousephd** [comment]
After talking with Michael Love, one of the author's of DESeq2, I've adopted the following:
```
dds <- DESeq(dds, parallel = TRUE)
res <- results(dds)
shrunken <- lfcShrink(dds, contrast = c("group", trtment, referent)) ## lfcShrink is best for getting a "best" log2fc value
non_shrunken <- results(dds, contrast = c("group", trtment, referent)) ## The results function is better for getting the pvalues
## replace the l2fc values in the non_shrunken output with those gotten from shrunken
non_shrunken@listData$log2FoldChange <- non_shrunken@listData$log2FoldChange  ### replace L2fc estimates with shrunken ones ###

```
Then your non_shrunken has the correct l2fc and pvals, adj.pvals etc...

**Comment by gr8lly8** [comment]
Hi John, 

Thank you for this, I have given it a go.  For the line:
shrunken <- lfcShrink(dds, contrast = c("group", trtment, referent))

I am getting the error:
Error in results(dds, contrast=contrast) : object 'trtment' not found

Best Wishes, 
Grace

**Comment by gr8lly8** [comment]
Hi John, 

Did you have any advice on the above error? 

Thank you, 
Grace

**Comment by jshousephd** [comment]
Good morning. I missed this 5 days ago.  

You will need to replace referent and trtment with the values of the group variable you defined for which you want to make a comparison. Or assign them before running the contrast statements. 

For example:

`shrunken <- lfcShrink(dds, contrast = c("group", "Dofetilide", "VEHICLE"))` will compare Dofetilide to VEHICLE.  

In the scripts, group was defined as any dose of the treatment. This means the comparison will be for all doses of treatment vs. the control.  I need to look further, but this appears to be a mistake on my part. I was intending these contrasts to examine max dose of the treatments. 

This would require replacing line 23 with the following: `qc_hash$group <- factor(paste0(qc_hash$group,"_",qc_hash$DOSE))` and line 48 with `treatment$control <- "VEHICLE_0"`

Then the contrast statement would change to: `contrast = c("group", "Dofetilide", "VEHICLE_0")
Sorry for the confusion.

**Comment by gr8lly8** [comment]
Hi John, 

I'm afraid I then get a new error:
Error in cleanContrast(object, contrast, expanded = isExpanded, listValues = listValues,  : 
  Dofetilide and VEHICLE should be levels of group such that group_Dofetilide_vs_Dofetilide_0.1 and group_VEHICLE_vs_Dofetilide_0.1 are contained in 'resultsNames(object)'

Maybe I'm missing something?

qc_hash$group <- factor(paste0(qc_hash$group,"_",qc_hash$DOSE))

dds = DESeqDataSetFromMatrix(countData = qc_counts,
                             colData = qc_hash,
                             design = ~ group)

dds <- DESeq(dds, parallel = TRUE)
res <- results(dds)
shrunken <- lfcShrink(dds, contrast = c("group", "Dofetilide", "VEHICLE_0")) 
non_shrunken <- results(dds, contrast = c("group", "Dofetilide", "VEHICLE_0")) 
non_shrunken@listData$log2FoldChange <- non_shrunken@listData$log2FoldChange


Best Wishes, 
Grace

**Comment by jshousephd** [comment]
Hi Grace,
Please see below. I've rewritten the code to address two issues. 

1. The way that the DESeq() comparison was made originally was actually comparing all doses of one of the drugs to the control to evaluate for differences. This has been changed by how the `group` variable is defined.  The new line for this is `qc_hash$group <- paste0(qc_hash$Treatment, "_", round(qc_hash$numeric_dose,0))`.  **NOTE: This causes the number of DEGs to be different from the examples.**
2. The `lfcShrink()` changes made to DESeq2 where we really want L2FC values from `lfcShrink()`, but pvalues from `results()`.  I've written a function `DESeq2_sContrast()` that does the following:

- Create a MA Plot showing the Differentially expressed genes for the comparions
- Use the lfcShrink() function to get the l2fc values
- Use the results() function to get pvalues, adj.pvalues etc..
- Combined into a dataset for all genes tested for that comparison and write a .csv
- Return that dataset to an object in memory 

Thanks for bringing this to my attention.
Best,
john

```
package.list <- c("DESeq2", "BiocParallel", "dplyr", "ggplot2")
if (length(setdiff(package.list, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(package.list, rownames(installed.packages())))
}
lapply(package.list, require, character.only = TRUE)
setwd("C:/Users/jshou/Google Drive/TempOSeq_Pipeline/ht_cba_manuscript")

load("Output Files/Cleaned_data/qc_counts.RData")
load("Output Files/Cleaned_data/qc_hash.RData")

qc_hash$group <- paste0(qc_hash$Treatment, "_", round(qc_hash$numeric_dose,0))
qc_hash$group <- factor(qc_hash$group)
## group was defined as one level up from the lowest (replicate) ##
## you can define another level to test if you like ##
## this experimental design still assumes that there are different media controls on each Index.Set ##
dds = DESeqDataSetFromMatrix(countData = qc_counts,
                             colData = qc_hash,
                             design = ~ group)

system.time(dds <- DESeq(dds, parallel = TRUE))
save(dds, file = "Output Files/DESeq2 dds Files/full_dds.RData")
normcounts <- counts(dds, normalized = TRUE)
write.csv(normcounts, file = "Output Files/Cleaned_data/normcounts.csv")
save(normcounts, file = "Output Files/Cleaned_data/normcounts.RData")

### This is needed for the following function ###
results_dds <- results(dds)

DESeq2_sContrast <- function(deseq_ds = dds, trt, ref, trt_label=trt, ref_label=ref, results_ds = results_dds) {
  testshrunk<-lfcShrink(deseq_ds, contrast = c("group",trt,ref), res = results_ds) ## we want shrunken l2fc ###
  test <- results(deseq_ds, contrast = c("group",trt,ref),parallel = T)  ### everything else is from un-shrunken ###
  test@listData$log2FoldChange <- testshrunk@listData$log2FoldChange  ### replace L2fc estimates with shrunken ones ###
  testdf<-as.data.frame(test);  total<- sum(testdf$padj<.1,na.rm=T)
  testdf$trt <- paste0(trt,"_vs_",ref)
  testdf$Treatment <- paste0(trt_label, " vs. ", ref_label)
  testdf$gene<-rownames(testdf); testdf$id<-paste0(testdf$gene,"/",testdf$Treatment)
  rownames(testdf)<-NULL
  write.csv(testdf,file = paste0("Output Files/MaxDoseContrasts/", trt,"_",ref,".csv"))
  p <- plotMA(test,alpha=0.10, main=paste0(trt_label, " vs. ", ref_label," DEGs = ",total), cex=1,ylim=c(-4,4),cex.main=.9)
  print(p)
  return(testdf)
}
## This function will:
# 1) Create a MA Plot showing the Differentially expressed genes for the comparions
# 2) Use the lfcShrink() function to get the l2fc values
# 3) Use the results() function to get pvalues, adj.pvalues etc..
# 4) Combined into a dataset for all genes tested for that comparison and write a .csv
# 5) return that dataset to an object in memory (i.e. - Dof_10_DEG)
Dof_10_DEG <- DESeq2_sContrast(deseq_ds = dds,
                               trt = "Dofetilide_10",
                               ref = "VEHICLE_0",
                               trt_label = "Max.Dose Dofetilide",
                               ref_label = "Control",
                               results_ds = results_dds)

### feel free to put a wrapper around it for printing PDF's of the graphs ###
pdf(file = "test.pdf", height = 10, width = 10)
par(mfrow = c(2,2)) #set graphs to be a 2 by 2 grid
myds1 <- DESeq2_sContrast( trt = "Dofetilide_10",
                  ref = "VEHICLE_0") 
myds2 <- DESeq2_sContrast( trt = "Isoproterenol_10",
                  ref = "VEHICLE_0")
myds3 <- DESeq2_sContrast( trt = "Nifedipine_10",
                  ref = "VEHICLE_0")
myds4 <- DESeq2_sContrast( trt = "Propranolol_10",
                  ref = "VEHICLE_0")
dev.off()

combined_maxdose <- rbind(myds1, myds2, myds3, myds4)
combined_maxdose$Treatment <- factor(combined_maxdose$Treatment)
save(combined_maxdose, file = "Output Files/MaxDoseContrasts/combined_maxdose.RData")
write.csv(combined_maxdose, file = "Output Files/MaxDoseContrasts/combined_maxdose.csv")
```

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggplot2_3.0.0               dplyr_0.7.6                 DESeq2_1.20.0               SummarizedExperiment_1.10.1
 [5] DelayedArray_0.6.3          BiocParallel_1.14.2         matrixStats_0.54.0          Biobase_2.40.0             
 [9] GenomicRanges_1.32.6        GenomeInfoDb_1.16.0         IRanges_2.14.10             S4Vectors_0.18.3           
[13] BiocGenerics_0.26.0         RevoUtils_11.0.0            BiocInstaller_1.30.0        RevoUtilsMath_11.0.0       


```
